ALTER TABLE clients ADD COLUMN IF NOT EXISTS organization_name VARCHAR(255);
ALTER TABLE clients ADD COLUMN IF NOT EXISTS address_door VARCHAR(100);
ALTER TABLE clients ADD COLUMN IF NOT EXISTS address_city VARCHAR(100);
ALTER TABLE clients ADD COLUMN IF NOT EXISTS address_district VARCHAR(100);
ALTER TABLE clients ADD COLUMN IF NOT EXISTS address_state VARCHAR(100);
ALTER TABLE clients ADD COLUMN IF NOT EXISTS address_pincode VARCHAR(20);
