-- Seed Services
INSERT INTO services (name, code, description, starting_number_sequence) VALUES
('Web Development', 'WEBD', 'Custom websites and web applications', 27),
('App Development', 'APPD', 'iOS and Android mobile applications', 4),
('AI Solutions', 'AIOL', 'Artificial Intelligence and Machine Learning models', 1),
('Academic Assistance', 'ACAD', 'Research guidance and thesis support', 1)
ON CONFLICT (code) DO NOTHING;

-- Seed Initial Admin User (Password: admin123 - needs to be hashed in real app, but for seed we will assume app handles hash or we verify logic)
-- hash for 'admin123': $2a$10$X7V.j5qj.X7V.j5qj.X7V.j5qj.X7V.j5qj.X7V.j5qj.X7V.j5qj (This is fake, inserting dummy for now, will implement registration or initial hash in code)
-- Actually, let's insert a known hash for 'admin123' generated by bcryptjs
-- $2a$10$wIzXJ/../.. (We will create a script to seed this via Node.js for proper hashing, or just insert a placeholder and user must update)

-- Let's just create the entry, we can reset password later or use a known hash.
-- $2a$10$r.7/.. is not easy to guess. 
-- I will create a seeder script in Node.js instead of raw SQL for the user to ensure password is correct.
